# server:
#   port: ${SERVER_PORT:8080}

# spring:
#   main:
#     allow-bean-definition-overriding: true
#     web-application-type: reactive  application:
#     name: lightweight-gateway
#   security:
#     jwt:
#       secret: ${JWT_SECRET:58703273357638792F423F4528482B4D6251655468576D5A7134743677397A24}
#       expiration: ${JWT_EXPIRATION:86400000}
#   cloud:
#     gateway:
#       default-filters:
#         - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
#       globalcors:
#         cors-configurations:
#           '[/**]':
#             allowedOrigins: "*"
#             allowedMethods: "*"
#             allowedHeaders: "*"
#       routes:
#         - id: auth_route
#           uri: http://localhost:8090
#           predicates:
#             - Path=/auth/**
#           filters:
#             - PreserveHostHeader
        
#         - id: protected_routes
#           uri: http://localhost:8090
#           predicates:
#             - Path=/ipay/**
#           filters:
#             - name: JwtAuthentication
#             - AddRequestHeader=X-Gateway-Source, api-gateway
#             - PreserveHostHeader

# # Configuration URLs for OpenAPI
# openapi:
#   dev-url: http://localhost:8080
#   prod-url: https://api.innov4africa.sn

# logging:
#   level:
#     com.innov4africa: DEBUG
#     org.springframework.web.reactive: DEBUG
#     reactor.netty: DEBUG
#     org.springframework.cloud.gateway: DEBUG
#     org.springframework.security: DEBUG
server:
  port: ${SERVER_PORT:8080}

spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 60000
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: lightweight-gateway
  security:
    jwt:
      secret: ${JWT_SECRET:58703273357638792F423F4528482B4D6251655468576D5A7134743677397A24}
      expiration: ${JWT_EXPIRATION:86400000}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth_route
          uri: http://localhost:8090
          predicates:
            - Path=/auth/**
          filters:
            - PreserveHostHeader
        
        - id: protected_routes
          uri: http://localhost:8090
          predicates:
            - Path=/ipay/**, /ishop/**, /ibanking/**
          filters:
            - name: JwtAuthentication
            - name: RequestTransformation
            - name: ResponseTransformation
            - AddRequestHeader=X-Gateway-Source, api-gateway
            - PreserveHostHeader

logging:
  level:
    com.innov4africa: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

openapi:
  dev-url: http://localhost:8080
  prod-url: https://api.innov4africa.sn